twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    file_name_pattern: '*.twig'
    globals:
        cultures: '@App\Service\CultureService'
        sets: '@App\Service\PublishedSetService'

when@test:
    twig:
        strict_variables: true
